# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 


from pathlib import Path

# absolute path to snakemake dir
snakemake_dir = Path(workflow.snakefile).parent.resolve()
# include default config values
configfile: f"{snakemake_dir.parent}/config/default_config.yaml"





include: "rules/input_functions.smk"
include: "rules/sylph.smk"

rule all:
    input:
        expand("Sylph/{dbname}_abundance.csv", dbname = config['dbs_for_profiling']),
        #expand("Sylph/{dbname}_{method}.tsv", dbname= ["refseq_fungi","img_vr4"],method="profile"),
        #expand("Sylph/{dbname}_{method}.tsv", dbname= "uhgg",method="query"),
        
        